const SETTINGS = {
	gameWidth: 1280,
	gameHeight: 800,
	tileSize: 40,
	tickSpeed: 30,
	socketTickSpeed: 20,
	GAME: {
		RESPAWN_TIME: 3000,
		BOOST_POWER: 28,
		BOOST_RESPAWN_TIME: 5000,
		BOMB_RANGE: 150,
		BOMB_POWER: 0.036,
		BOMB_RESPAWN_TIME: 5000,
		FC_INVINCIBLE_TIME: 250,
		TEAMTILE_AIR_FRICTION: 0.012,
		TEAMTILE_TOP_VELOCITY: 20,
		POOST_RANGE: 40,
		POOST_POWER: 0.01,
		POWERUP_LIFETIME: 20000,
		POWERUP_RESPAWN_TIME: 5000,
		CONTACT_BOMB_RANGE: 70,
		CONTACT_BOMB_POWER: 0.025,
		ENERGIZER_ACCELERATION_MULTIPLIER: 1.25,
		GAME_LENGTH_SECONDS: 8 * 60,
		GAME_COUNTDOWN_SECONDS: 15
	},
	BALL: {
		SIZE: 19,
		ACCELERATION: 0.0008,
		DENSITY: 0.006,
		BOUNCINESS: 0.2,
		TOP_VELOCITY: 24,
		FRICTION: 0.3,
		AIR_FRICTION: 0.02
	},
	TEAM: {
		NONE: 0,
		RED: 1,
		BLUE: 2,
		NEUTRAL: 3
	},
	EVENTS: {
		PLAYER_LEFT: 1,
		PLAYER_POPPED: 2,
		GAME_STOPPED: 3
	},
	POWERUPS: {
		FORCEFIELD: 1,
		CONTACT_BOMB: 2,
		ENERGIZER: 3
	},
	TILE_IDS: {
		BACKGROUND: 0,
		FLOOR: 1,
		WALL: 2,
		WALLTL: 2.1,
		WALLTR: 2.2,
		WALLBL: 2.3,
		WALLBR: 2.4,
		REDFLAG: 3.1,
		BLUEFLAG: 3.2,
		REDSPAWN: 4.1,
		BLUESPAWN: 4.2,
		SPIKE: 5,
		BOOST: 6,
		REDBOOST: 6.1,
		BLUEBOOST: 6.2,
		BOMB: 7,
		BUTTON: 8,
		NONEGATE: 9,
		NEUTRALGATE: 9.1,
		REDGATE: 9.2,
		BLUEGATE: 9.3,
		NEUTRALTEAMTILE: 10,
		REDTEAMTILE: 10.1,
		BLUETEAMTILE: 10.2,
		PORTAL: 11,
		POWERUP: 12
	},
	ELEMENT_SIZES: {
		FLOOR: 40,
		FLAG: 15,
		SPIKE: 14,
		BOOST: 15,
		BOMB: 15,
		BUTTON: 8,
		GATE: 40,
		PORTAL: 15,
		POWERUP: 15
	},
	MESSENGER_KEYS: {
		PLAYER: ["id", "name", "x", "y", "xVelocity", "yVelocity", "rotation", "team", "hasFlag", "dead", "powerups"]
	}
};

module.exports = SETTINGS;